Repository loopcrack-org/Kinub, pull requests merged in 2023-08, with the labels that each got.

#1 KIN-183 Added repository documentation and PR process enhancements
  .github/CODEOWNERS
  .github/pr-badge.yml
  .github/pull_request_template.md
  README.md
Labels: Setup

#6 KIN-162 Create the Mail Table on the Database
  app/Database/Seeds/EmailSeeder.php
  backup/Database.sql
Labels: Database

#9 KIN-186 Error when executing the watchFiles gulp task.
  .gitignore
  gulpfile.js
  public/assets/css/admin.min.css.map
  public/assets/css/bootstrap.min.css.map
  public/assets/css/public.min.css.map
  public/assets/js/admin/app.js.map
  public/assets/js/admin/layout.js.map
Labels: bug

#7 KIN-159 Contact Form Data Validation Homepage
  app/Config/Routes.php
  app/Controllers/CtrlEmail.php
  app/Controllers/CtrlPublicPages.php
  app/Validation/ContactEmailValidation.php
Labels: Backend

#13 KIN-80 added contact form layout
  app/Views/public/index.php
  app/Views/public/templates/layout.php
  public/assets/css/public.min.css
  src/sass/public/UI/_index.scss
  src/sass/public/UI/form/_form.scss
  src/sass/public/UI/form/_index.scss
  src/sass/public/app.scss
  src/sass/public/base/_global.scss
  src/sass/public/base/_index.scss
  src/sass/public/base/_mixins.scss
  src/sass/public/base/_normalize.scss
  src/sass/public/base/_typography.scss
  src/sass/public/base/_variables.scss
Labels: Frontend, Public

#11 KIN-147 Create Controller for Support Form Validation
  app/Config/Routes.php
  app/Controllers/CtrlEmail.php
  app/Controllers/CtrlPublicPages.php
  app/Validation/SupportEmailValidation.php
Labels: Backend

#14 KIN-163 Routing Login Page
  app/Config/Routes.php
  app/Controllers/CtrlEmail.php
  app/Controllers/CtrlLogin.php
  app/Views/login/PasswordEmail.php
  app/Views/login/PasswordReset.php
  app/Views/login/index.php
Labels: Backend

#15 KIN-109 Added login page layout
  app/Views/login/index.php
  app/Views/partials/title-meta.php
  public/assets/js/pages/particles.app.js
  public/assets/js/pages/password-addon.init.js
  public/assets/libs/particles/particles.js
  src/js/admin/pages/particles.app.js
  src/js/admin/pages/password-addon.init.js
Labels: Frontend, Private

#16 KIN-160 Sending the mail with the form data homepage
  .env.example
  app/Controllers/CtrlEmail.php
  app/Views/mailDetail.php
Labels: Backend

#18 KIN-183 CODEOWNERS fix
  .github/CODEOWNERS
Labels: bug, Setup

#17 KIN-178 User Table and UserSeeder
  app/Database/Seeds/EmailSeeder.php
  app/Database/Seeds/UserSeeder.php
  backup/Database.sql
Labels: Private, Database

#20 KIN-161 Creation of the email model and storage of information
  app/Controllers/CtrlEmail.php
  app/Models/EmailModel.php
Labels: Backend

#19 KIN-188 Gulpfile fix
  README.md
  gulpfile.js
  package.json
  src/js/pages/particles.app.js
  src/js/pages/password-addon.init.js
Labels: bug, Setup

#23 KIN-110 Login form logic - login page
  app/Controllers/CtrlLogin.php
  app/Database/Seeds/UserSeeder.php
  app/Models/UserModel.php
  app/Validation/BaseValidation.php
  app/Validation/LoginValidation.php
  app/Views/login/index.php
Labels: Backend

#24 KIN-191 Change the implementation of sendEmail
  app/Controllers/CtrlEmail.php
Labels: Backend

#25 KIN-115 Add change password page
  app/Views/login/PasswordReset.php
  public/assets/js/pages/passowrd-create.init.js
  src/js/pages/passowrd-create.init.js
Labels: Frontend, Private

#26 KIN-189 Malformed Jira Badge URL correction
  .github/pr-badge.yml
Labels: Setup
