Repository loopcrack-org/Kinub, pull requests merged in 2023-12, with the labels that each got.

#137 KIN-309 refactor CSS technical support page
  .eslintignore
  app/Controllers/CtrlEmail.php
  app/Views/public/certificates.php
  app/Views/public/equipment.php
  app/Views/public/support.php
  app/Views/public/templates/footer.php
  public/assets/libs/vanilla-validator/vanilla-validator-concat.min.js
  src/public/js/product.js
  src/public/js/support.js
  src/public/libs/vanilla-js-accordions/AccordionElement.min.js
  src/public/libs/vanilla-validator/vanilla-validator-concat.js
  src/public/old_sass/UI/filter/_filter.scss
  src/public/old_sass/UI/filter/_index.scss
  src/public/old_sass/UI/filter/_multiple-options-select.scss
  src/public/old_sass/UI/pagination/_index.scss
  src/public/old_sass/UI/product/_header.scss
  src/public/old_sass/UI/product/_index.scss
  src/public/old_sass/UI/product/_modal-form.scss
  src/public/old_sass/UI/product/_product-carousel.scss
  src/public/old_sass/UI/product/_product-info.scss
  src/public/old_sass/UI/support/_index.scss
  src/public/old_sass/UI/support/_support.scss
  src/public/old_sass/certificates.scss
  src/public/old_sass/pagination.scss
  src/public/old_sass/product.scss
  src/public/sass/ITCSS/01_settings/_colors.scss
  src/public/sass/ITCSS/01_settings/_global.scss
  src/public/sass/ITCSS/02_tools/__index.scss
  src/public/sass/ITCSS/02_tools/_keyframes.scss
  src/public/sass/ITCSS/03_generic/_root-variables.scss
  src/public/sass/ITCSS/04_elements/_forms.scss
  src/public/sass/ITCSS/05_objects/_title.scss
  src/public/sass/ITCSS/06_components/_footer.scss
  src/public/sass/ITCSS/06_components/pages/support/__index.scss
  src/public/sass/ITCSS/06_components/pages/support/_support-form.scss
  src/public/sass/ITCSS/06_components/pages/support/_support-progress.scss
  src/public/sass/ITCSS/06_components/pages/support/_support.scss
  src/public/sass/ITCSS/07_utilities/__flex.scss
  src/public/sass/Pages/support.scss
  src/public/sass/plugins/_intl-tel-input.scss
Labels: frontend, public, enhancement

#142 KIN-202 Add category edit functionality without file management
  app/Controllers/CtrlCategory.php
  app/Models/CategoryModel.php
Labels: backend

#141 KIN-353 Added Security Headers to Website
  htaccess.production
Labels: enhancement, setup

#139 KIN-314 refactor styles certificates page
  app/Views/public/certificates.php
  src/public/sass/ITCSS/01_settings/_global.scss
  src/public/sass/ITCSS/05_objects/_title.scss
  src/public/sass/ITCSS/06_components/pages/certificates/__index.scss
  src/public/sass/ITCSS/06_components/pages/certificates/_certificate.scss
  src/public/sass/ITCSS/06_components/pages/certificates/_certificates.scss
  src/public/sass/Pages/certificates.scss
Labels: frontend, public

#148 KIN-256 Files manage
  .gitignore
  app/Classes/ClientValidationConfig.php
  app/Classes/ClientValidationConfigBuilder.php
  app/Classes/FileValidationConfig.php
  app/Classes/FileValidationConfigBuilder.php
  app/Classes/ServerValidationConfig.php
  app/Classes/ServerValidationConfigBuilder.php
  app/Config/Constants.php
  app/Config/Routes.php
  app/Config/Validation.php
  app/Controllers/BaseController.php
  app/Controllers/CtrlApiFiles.php
  app/Controllers/CtrlPublicPages.php
  app/Exceptions/FileValidationException.php
  app/Interfaces/Filepond.php
  app/Interfaces/ValidationConfigBuilder.php
  app/Libraries/fileValidation/FileRules.php
  app/Models/FileModel.php
  app/Utils/FileManager.php
  app/Validation/BaseValidation.php
  app/Views/admin/components/errorAlert.php
  app/Views/admin/components/inputFilePond.php
  gulpfile.js
  package-lock.json
  package.json
  src/admin/js/app.js
  src/admin/js/pages/plugins/filepond/_alerts.js
  src/admin/js/pages/plugins/filepond/_config.js
  src/admin/js/pages/plugins/filepond/_validations.js
  src/admin/js/pages/plugins/filepond/filepond-general-config.js
  src/admin/sass/plugins/_choices.scss
  src/admin/sass/plugins/filepond/filepond.scss
Labels: backend, help wanted, setup

#149 KIN-367 fix variable issue on certificates page
  src/public/sass/ITCSS/01_settings/_global.scss
  src/public/sass/ITCSS/06_components/pages/certificates/_certificate.scss
Labels: public

#144 KIN-210: Edit measurement solution functionality
  app/Controllers/CtrlSolution.php
  app/Models/MeasurementSolutionModel.php
  app/Views/admin/typeSolutions/solutionsFormTemplate.php
Labels: backend, private

#133 KIN-312: refactor styles of product page
  .vscode/extensions.json
  app/Views/public/product.php
  src/public/js/magnify.js
  src/public/js/product.js
  src/public/sass/ITCSS/01_settings/_colors.scss
  src/public/sass/ITCSS/01_settings/_global.scss
  src/public/sass/ITCSS/06_components/pages/product/.gitkeep
  src/public/sass/ITCSS/06_components/pages/product/__index.scss
  src/public/sass/ITCSS/06_components/pages/product/_details.scss
  src/public/sass/ITCSS/06_components/pages/product/_product-nav.scss
  src/public/sass/ITCSS/06_components/pages/product/_tags.scss
  src/public/sass/ITCSS/06_components/pages/product/carousel/__index.scss
  src/public/sass/ITCSS/06_components/pages/product/carousel/_carousel.scss
  src/public/sass/ITCSS/06_components/pages/product/carousel/_glide.scss
  src/public/sass/ITCSS/06_components/pages/product/carousel/_magnify-wrapper.scss
  src/public/sass/ITCSS/06_components/pages/product/modal-form/__index.scss
  src/public/sass/ITCSS/06_components/pages/product/modal-form/_modal-form.scss
  src/public/sass/ITCSS/06_components/pages/product/modal-form/_tingle-modal-box.scss
  src/public/sass/ITCSS/06_components/pages/product/modal-form/_tingle-modal.scss
  src/public/sass/ITCSS/06_components/pages/product/product-info/__index.scss
  src/public/sass/ITCSS/06_components/pages/product/product-info/_download-area.scss
  src/public/sass/ITCSS/06_components/pages/product/product-info/_product-info.scss
  src/public/sass/Pages/product.scss
  src/public/sass/plugins/_lightgallery.scss
  src/public/sass/plugins/_plyr.scss
  src/public/sass/plugins/_tingle.scss
Labels: frontend, public

#150 KIN-334 Add files functionality in AboutUs section
  app/Config/Routes.php
  app/Controllers/CtrlAboutUs.php
  app/Controllers/CtrlApiFiles.php
  app/Models/FileModel.php
  app/Models/HomeSectionModel.php
  app/Views/admin/aboutUs/AboutUsEdit.php
  public/files/tmp/3ea307c224811d55048d72b5696895eb/auth-one-bg.jpg
  public/uploads/3ea307c224811d55048d72b5696895eb/auth-one-bg.jpg
  src/admin/js/pages/aboutUs.init.js
Labels: backend

#147 KIN-290 Add resend email to confirm account functionality
  app/Config/Routes.php
  app/Controllers/CtrlEmail.php
  app/Controllers/CtrlUser.php
  app/Exceptions/EmailNotSendException.php
  app/Models/UserModel.php
  app/Models/UserTokenModel.php
  app/Utils/TokenGenerator.php
  app/Views/admin/users/UserEdit.php
  app/Views/admin/users/Users.php
  src/admin/js/pages/alertToResendConfirmAccountEmail.js
Labels: backend, frontend, private

#143 KIN-219 Add delete category functionality without files management
  app/Controllers/CtrlCategory.php
  app/Models/CategoryModel.php
  app/Views/admin/categories/Categories.php
Labels: backend

#157 KIN-362, KIN-363, KIN-364, KIN-366 Improve all pages designs
  app/Validation/ContactEmailValidation.php
  app/Views/public/category.php
  app/Views/public/certificates.php
  app/Views/public/equipment.php
  app/Views/public/index.php
  branch-name-lint.json
  package-lock.json
  package.json
  public/assets/images/pdf-example.png
  public/assets/images/pdf-horizontal-example.jpg
  src/public/js/home.js
  src/public/js/product.js
  src/public/sass/ITCSS/01_settings/_global.scss
  src/public/sass/ITCSS/05_objects/__index.scss
  src/public/sass/ITCSS/05_objects/_kinub-card.scss
  src/public/sass/ITCSS/05_objects/_title.scss
  src/public/sass/ITCSS/06_components/_btn-whatsapp.scss
  src/public/sass/ITCSS/06_components/_footer.scss
  src/public/sass/ITCSS/06_components/_jumbotron.scss
  src/public/sass/ITCSS/06_components/header/_header.scss
  src/public/sass/ITCSS/06_components/header/_navigation.scss
  src/public/sass/ITCSS/06_components/pages/category/_category.scss
  src/public/sass/ITCSS/06_components/pages/category/_product.scss
  src/public/sass/ITCSS/06_components/pages/certificates/_certificate.scss
  src/public/sass/ITCSS/06_components/pages/certificates/_certificates.scss
  src/public/sass/ITCSS/06_components/pages/equipment/_equipments.scss
  src/public/sass/ITCSS/06_components/pages/equipment/content/_content.scss
  src/public/sass/ITCSS/06_components/pages/equipment/content/_equipment.scss
  src/public/sass/ITCSS/06_components/pages/home/_about-us.scss
  src/public/sass/ITCSS/06_components/pages/home/form/__index.scss
  src/public/sass/ITCSS/06_components/pages/home/form/_custom-select.scss
  src/public/sass/ITCSS/06_components/pages/home/form/_form-container.scss
  src/public/sass/ITCSS/06_components/pages/home/form/_form.scss
  src/public/sass/ITCSS/06_components/pages/home/kinub-video/_kinub-video.scss
  src/public/sass/ITCSS/06_components/pages/home/measurement-solutions/__index.scss
  src/public/sass/ITCSS/06_components/pages/home/measurement-solutions/_measurement-solution.scss
  src/public/sass/ITCSS/06_components/pages/home/measurement-solutions/_measurement-solutions.scss
  src/public/sass/ITCSS/06_components/pages/home/measurement-solutions/_swiper.scss
  src/public/sass/ITCSS/06_components/pages/product/_product-nav.scss
  src/public/sass/ITCSS/06_components/pages/product/product-info/_download-area.scss
  src/public/sass/ITCSS/06_components/pages/product/product-info/_product-info.scss
  src/public/sass/Pages/home.scss
Labels: frontend, public

#158 KIN-370: Privacy Policy Page Layout
  app/Config/Routes.php
  app/Controllers/CtrlPublicPages.php
  app/Views/public/privacy-policy.php
  app/Views/public/templates/footer.php
  src/public/sass/ITCSS/06_components/pages/privacy-policy/__index.scss
  src/public/sass/ITCSS/06_components/pages/privacy-policy/_privacy-policy.scss
  src/public/sass/Pages/privacy-policy.scss
Labels: frontend, public

#156 KIN-335: Files Management Functionality on Measurement Solutions CRUD
  app/Config/Routes.php
  app/Controllers/CtrlSolution.php
  app/Database/Migrations/2023-10-17-221601_MeasurementSolutions.php
  app/Models/MeasurementSolutionModel.php
  app/Views/admin/typeSolutions/SolutionCreate.php
  app/Views/admin/typeSolutions/SolutionEdit.php
  app/Views/admin/typeSolutions/solutionsFormTemplate.php
  src/admin/js/pages/form-file-upload-measurementSolution.init.js
Labels: backend, private

#151 KIN-338 functionality to create certificates with files
  app/Classes/ServerValidationConfigBuilder.php
  app/Config/Routes.php
  app/Controllers/CtrlCertificate.php
  app/Models/CertificateModel.php
  app/Views/admin/certificates/CertificateCreate.php
  app/Views/admin/certificates/certificatesFormTemplate.php
Labels: backend, private

#160 KIN-336 Add files managament in categories crud
  app/Config/Routes.php
  app/Controllers/CtrlCategory.php
  app/Database/Migrations/2023-10-17-220959_Categories.php
  app/Models/CategoryModel.php
  app/Views/admin/categories/Categories.php
  app/Views/admin/categories/CategoryCreate.php
  app/Views/admin/categories/CategoryEdit.php
  app/Views/admin/categories/categoriesFormTemplate.php
Labels: backend, private

#165 KIN-374 Add min and max files validation
  app/Controllers/CtrlAboutUs.php
Labels: backend

#163 KIN-371 empty tables text
  src/admin/js/pages/datatables-general-config.js
Labels: bug

#161 KIN-320: Improve logo and particles effect login page
  app/Controllers/CtrlLogin.php
  app/Views/login/PasswordEmail.php
  app/Views/login/PasswordReset.php
  app/Views/login/PasswordResponse.php
  app/Views/login/PasswordSet.php
  app/Views/login/index.php
  app/Views/login/response.php
  src/admin/js/pages/particles.app.js
Labels: frontend, private

#166 KIN-304 edit certificate functionality with files
  app/Controllers/CtrlCertificate.php
  app/Models/CertificateModel.php
  app/Views/admin/certificates/CertificateEdit.php
  app/Views/admin/certificates/certificatesFormTemplate.php
  src/admin/js/alertElement.js
Labels: backend, private

#153 KIN-368 Improve caroussel and product details styles
  app/Views/public/index.php
  app/Views/public/product.php
  package-lock.json
  package.json
  src/public/js/components/carousel.js
  src/public/js/components/carouselUpdate.js
  src/public/js/components/productDetailsSection.js
  src/public/js/components/productModalForm.js
  src/public/js/components/swiper.js
  src/public/js/home.js
  src/public/js/light.js
  src/public/js/magnify.js
  src/public/js/product.js
  src/public/sass/ITCSS/06_components/_btn-whatsapp.scss
  src/public/sass/ITCSS/06_components/_jumbotron.scss
  src/public/sass/ITCSS/06_components/pages/product/_details.scss
  src/public/sass/ITCSS/06_components/pages/product/_product-nav.scss
  src/public/sass/ITCSS/06_components/pages/product/_tags.scss
  src/public/sass/ITCSS/06_components/pages/product/carousel/__index.scss
  src/public/sass/ITCSS/06_components/pages/product/carousel/_carousel.scss
  src/public/sass/ITCSS/06_components/pages/product/carousel/_glide.scss
  src/public/sass/ITCSS/06_components/pages/product/carousel/_magnify-wrapper.scss
  src/public/sass/ITCSS/06_components/pages/product/carousel/external-plugins/__index.scss
  src/public/sass/ITCSS/06_components/pages/product/carousel/external-plugins/_drift-zoom-pane.scss
  src/public/sass/ITCSS/06_components/pages/product/carousel/external-plugins/_plyr.scss
  src/public/sass/ITCSS/06_components/pages/product/carousel/external-plugins/_swiper.scss
  src/public/sass/ITCSS/06_components/pages/product/modal-form/_tingle-modal.scss
  src/public/sass/ITCSS/06_components/pages/product/product-info/_product-info.scss
  src/public/sass/Pages/product.scss
  src/public/sass/plugins/_drift-zoom.scss
Labels: frontend, public

#159 KIN-121 Create product view products page frontend
  app/Config/Routes.php
  app/Controllers/CtrlApiPublic.php
  app/Controllers/CtrlProduct.php
  app/Models/CategoryTagModel.php
  app/Views/admin/components/inputFilePond.php
  app/Views/admin/components/keyValue/keyValueContainer.php
  app/Views/admin/components/keyValue/keyValueInput.php
  app/Views/admin/components/keyValueInput.php
  app/Views/admin/products/ProductCreate.php
  app/Views/admin/products/productsFormTemplate.php
  package-lock.json
  package.json
  src/admin/js/app.js
  src/admin/js/pages/keyValueInput.js
  src/admin/js/pages/plugins/choices/choices-general-config.js
  src/admin/js/pages/plugins/wysiwyg/wysiwyg-general-config.js
  src/admin/js/pages/productChoices.js
  src/admin/sass/config/app.scss
  src/admin/sass/plugins/_choices.scss
  src/admin/sass/plugins/_quilljs.scss
  src/admin/sass/plugins/choices/choices.scss
  src/admin/sass/plugins/tippy/tippy.scss
  src/admin/sass/plugins/wysiwyg/wysiwyg.scss
  src/common/sass/bootstrap.scss
  src/common/sass/config/_variables.scss
Labels: frontend, private
