Repository loopcrack-org/Kinub, pull requests merged in 2023-11, with the labels that each got.

#95 KIN-211 delete measurement solution alert
  app/Controllers/CtrlSolution.php
  app/Views/admin/typeSolutions/Solutions.php
  src/admin/js/alertElement.js
  src/common/sass/sweetAlert.scss
Labels: frontend, private

#93 KIN-283 refactoring of the mails sent from the public view forms
  app/Views/mailDetail.php
Labels: frontend, public

#96 KIN-268 add delete user functionality
  app/Controllers/CtrlUser.php
  app/Views/admin/users/Users.php
  app/Views/templates/admin/deleteModalElement.php
  src/admin/js/deleteElement.js
Labels: backend, private

#99 KIN-280: Improve database seeding
  app/Database/Migrations/2023-10-17-221633_HomePage.php
  app/Database/Seeds/CategorySeeder.php
  app/Database/Seeds/CategoryTagSeeder.php
  app/Database/Seeds/CertificateSeeder.php
  app/Database/Seeds/EmailSeeder.php
  app/Database/Seeds/EmailTypeSeeder.php
  app/Database/Seeds/FileSeeder.php
  app/Database/Seeds/HomePageSeeder.php
  app/Database/Seeds/MainTestSeeder.php
  app/Database/Seeds/MeasurementSolutionSeeder.php
  app/Database/Seeds/ProductCategoryTagSeeder.php
  app/Database/Seeds/ProductFileSeeder.php
  app/Database/Seeds/ProductSeeder.php
  app/Database/Seeds/ProductTagSeeder.php
  app/Database/Seeds/UserSeeder.php
Labels: database

#97 KIN-267 do the create user functionality
  app/Controllers/CtrlEmail.php
  app/Controllers/CtrlUser.php
  app/Utils/TokenGenerator.php
  app/Validation/PasswordEmailValidation.php
  app/Validation/UserValidation.php
  app/Views/admin/users/UserCreate.php
  app/Views/admin/users/Users.php
Labels: backend, private

#102 KIN-236 Files API and Files Handler Class
  app/Config/Constants.php
  app/Config/Routes.php
  app/Controllers/CtrlApiFiles.php
  app/Utils/FileManager.php
Labels: backend, setup

#98 KIN-285 edit user functionality user page
  app/Controllers/CtrlUser.php
  app/Validation/UserValidation.php
  app/Views/admin/users/UserCreate.php
  app/Views/admin/users/UserEdit.php
Labels: backend, private

#101 KIN-287 Storing Inquirier Name and Email from public view forms
  app/Controllers/CtrlEmail.php
  app/Models/EmailModel.php
Labels: backend, public

#87 KIN-97 product page layout
  app/Config/Routes.php
  app/Controllers/CtrlPublicPages.php
  app/Views/public/index.php
  app/Views/public/product.php
  app/Views/public/templates/header.php
  package-lock.json
  package.json
  src/libs/vanilla-js-accordions/AccordionElement.min.js
  src/public/js/product.js
  src/public/sass/UI/header/_header.scss
  src/public/sass/UI/product/_header.scss
  src/public/sass/UI/product/_index.scss
  src/public/sass/UI/product/_product-info.scss
  src/public/sass/UI/whatsapp/_whatsapp.scss
  src/public/sass/app.scss
  src/public/sass/base/_global.scss
  src/public/sass/base/_mixins.scss
  src/public/sass/base/_variables.scss
  src/public/sass/certificates.scss
  src/public/sass/plugins/_accordion.scss
  src/public/sass/plugins/_plyr.scss
  src/public/sass/plugins/plyr.scss
  src/public/sass/product.scss
Labels: frontend, public

#103 KIN-138 Email Page Layout
  app/Config/Routes.php
  app/Controllers/CtrlAdminEmail.php
  app/Views/admin/emails/Emails.php
  src/admin/js/pages/email.js
Labels: frontend, private

#104 KIN-214 Filepond configuration from server
  .gitignore
  app/Config/Routes.php
  app/Controllers/CtrlApiFiles.php
  app/Controllers/CtrlTestFiles.php
  app/Utils/FileManager.php
  app/Views/admin/components/inputFilePond.php
  app/Views/admin/test/testFilesCreate.php
  package-lock.json
  package.json
  src/admin/js/pages/plugins/filepond/_alerts.js
  src/admin/js/pages/plugins/filepond/_config.js
  src/admin/js/pages/plugins/filepond/_validations.js
  src/admin/js/pages/plugins/filepond/filepond-general-config.js
  src/admin/sass/plugins/filepond/filepond.scss
Labels: backend, setup

#100 KIN-288: Integration of the token expiration feature on the database
  app/Controllers/CtrlEmail.php
  app/Controllers/CtrlLogin.php
  app/Controllers/CtrlUser.php
  app/Database/Migrations/2023-10-17-224407_Users.php
  app/Database/Migrations/2023-10-31-185106_UsersTokens.php
  app/Database/Seeds/MainTestSeeder.php
  app/Database/Seeds/UserSeeder.php
  app/Database/Seeds/UserTokensSeeder.php
  app/Models/UserModel.php
  app/Models/UserTokenModel.php
  app/Utils/TokenGenerator.php
  app/Validation/ChangePasswordValidation.php
Labels: private, database

#105 KIN-264 create certificate table
  app/Config/Routes.php
  app/Controllers/CtrlCertificate.php
  app/Models/CertificateModel.php
  app/Models/FileModel.php
  app/Views/admin/certificates/CertificateCreate.php
  app/Views/admin/certificates/CertificateEdit.php
  app/Views/admin/certificates/Certificates.php
  src/admin/js/pages/certificate.js
Labels: frontend, private

#107 KIN-299 File chunks implementation
  app/Config/Routes.php
  app/Controllers/CtrlApiFiles.php
  app/Controllers/CtrlTestFiles.php
  app/Utils/FileManager.php
Labels: backend, setup

#108 KIN-140 create the view specific emails page
  app/Config/Routes.php
  app/Controllers/CtrlAdminEmail.php
  app/Views/admin/emails/Emails.php
  app/Views/admin/emails/SpecificEmails.php
  app/Views/mailDetail.php
Labels: frontend, private

#109 KIN-322 Add edit about us section view
  app/Config/Routes.php
  app/Controllers/CtrlAboutUs.php
  app/Views/admin/aboutUs/AboutUsEdit.php
  app/Views/partials/sidebar.php
  src/admin/js/pages/aboutUs.init.js
Labels: frontend, private

#110 KIN-139 delete email alert
  app/Controllers/CtrlAdminEmail.php
  app/Views/admin/emails/Emails.php
Labels: frontend, private

#111 KIN-209: Edit measurement solution view
  app/Controllers/CtrlSolution.php
  app/Models/MeasurementSolutionModel.php
  app/Views/admin/typeSolutions/SolutionCreate.php
  app/Views/admin/typeSolutions/SolutionEdit.php
  app/Views/admin/typeSolutions/Solutions.php
  app/Views/admin/typeSolutions/solutionsFormTemplate.php
  app/Views/admin/users/UserEdit.php
Labels: backend, private

#113 KIN-327 Add meta tags for social media sharing
  app/Controllers/CtrlPublicPages.php
  app/Views/public/templates/layout.php
  public/assets/images/kinub-logo-meta.png
Labels: public, enhancement, setup

#112 KIN-265 create certificate page layout certificates page
  app/Controllers/CtrlCertificate.php
  app/Views/admin/certificates/CertificateCreate.php
  app/Views/admin/certificates/certificatesFormTemplate.php
  src/admin/js/pages/form-file-upload-certificate.init.js
Labels: frontend, private

#106 KIN-98: Modal Product Form Window
  app/Views/public/product.php
  package-lock.json
  package.json
  src/public/js/product.js
  src/public/sass/UI/product/_index.scss
  src/public/sass/UI/product/_modal-form.scss
  src/public/sass/base/_variables.scss
  src/public/sass/plugins/_tingle.scss
  src/public/sass/product.scss
Labels: frontend, public

#114 KIN-300 File Validations
  app/Config/Validation.php
  app/Controllers/CtrlApiFiles.php
  app/Controllers/CtrlTestFiles.php
  app/Exceptions/FileValidationException.php
  app/Libraries/fileValidation/FileRules.php
Labels: backend, setup

#117 KIN-323 Add edit about us functionality
  app/Controllers/CtrlAboutUs.php
  app/Database/Migrations/2023-10-17-221633_HomePage.php
  app/Exceptions/InvalidInputException.php
  app/Models/FileModel.php
  app/Models/HomeSectionModel.php
  app/Validation/AboutUsValidation.php
  app/Views/admin/aboutUs/AboutUsEdit.php
  app/Views/admin/templates/invalidInputError.php
  public/files/tmp/3ea307c224811d55048d72b5696895eb/auth-one-bg.jpg
Labels: backend

#118 KIN-297 edit certificate page layout certificates page
  app/Controllers/CtrlCertificate.php
  app/Views/admin/certificates/CertificateEdit.php
  app/Views/admin/certificates/certificatesFormTemplate.php
Labels: frontend, private

#119 KIN-315 create dashboard
  app/Views/admin/homeSection/HomeSection.php
Labels: frontend, private

#116 KIN-120 create products page layout
  app/Config/Routes.php
  app/Controllers/CtrlProduct.php
  app/Database/Migrations/2023-10-17-221706_Products.php
  app/Database/Migrations/2023-10-17-221724_ProductsFiles.php
  app/Database/Seeds/ProductFileSeeder.php
  app/Database/Seeds/ProductSeeder.php
  app/Models/ProductFilesModel.php
  app/Models/ProductModel.php
  app/Views/admin/products/ProductCreate.php
  app/Views/admin/products/ProductEdit.php
  app/Views/admin/products/Products.php
  src/admin/js/pages/product.js
Labels: frontend, private

#126 KIN-333 Added workflow for CI/CD
  .github/workflows/deploy.yml
Labels: enhancement, setup

#130 KIN-333 Added workflow for CI/CD Bug
  .github/workflows/deploy.yml
Labels: bug, enhancement, setup

#131 KIN-333 Added workflow for CI/CD Bug
  .github/workflows/deploy.yml
Labels: bug, enhancement, setup

#122 KIN-278 delete emails functionality email page
  app/Controllers/CtrlAdminEmail.php
  app/Views/templates/admin/deleteModalElement.php
  src/admin/js/deleteElement.js
Labels: backend, private

#120 KIN-99 add product image carousel
  app/Views/public/product.php
  package-lock.json
  package.json
  public/assets/fonts/lg.svg
  public/assets/fonts/lg.ttf
  public/assets/fonts/lg.woff
  public/assets/fonts/lg.woff2
  public/assets/images/loading.gif
  src/public/js/light.js
  src/public/js/magnify.js
  src/public/js/product.js
  src/public/sass/UI/product/_header.scss
  src/public/sass/UI/product/_index.scss
  src/public/sass/UI/product/_product-carousel.scss
  src/public/sass/base/_mixins.scss
  src/public/sass/product.scss
Labels: frontend, public

#121 KIN-208: Create Measurement Solution Functionality [Without Files Management]
  app/Controllers/CtrlSolution.php
  app/Validation/SolutionValidation.php
  app/Views/admin/typeSolutions/SolutionCreate.php
  app/Views/admin/typeSolutions/Solutions.php
  app/Views/admin/typeSolutions/solutionsFormTemplate.php
  src/admin/js/pages/form-file-upload-measurementSolution.init.js
Labels: backend, private

#129 KIN-298 delete certificate alert
  app/Controllers/CtrlCertificate.php
  app/Views/admin/certificates/Certificates.php
Labels: frontend, private

#132 KIN-311 refactor styles product catalog page
  app/Views/public/category.php
  app/Views/public/templates/pagination.php
  public/assets/images/Telemetria.jpeg
  public/assets/images/imagen-catalogo.png
  src/public/old_sass/UI/product/_product-carousel.scss
  src/public/old_sass/category.scss
  src/public/sass/ITCSS/02_tools/_mixins.scss
  src/public/sass/ITCSS/06_components/_jumbotron.scss
  src/public/sass/ITCSS/06_components/_pagination.scss
  src/public/sass/ITCSS/06_components/pages/category/__index.scss
  src/public/sass/ITCSS/06_components/pages/category/_category.scss
  src/public/sass/ITCSS/06_components/pages/category/_product.scss
  src/public/sass/Pages/category.scss
Labels: frontend, public

#127 KIN-200 Create Category Functionality
  app/Controllers/CtrlCategory.php
  app/Database/Migrations/2023-10-17-220959_Categories.php
  app/Models/CategoryModel.php
  app/Models/CategoryTagModel.php
  app/Validation/CategoryValidation.php
  app/Views/admin/categories/CategoryCreate.php
  app/Views/admin/categories/categoriesFormTemplate.php
  app/Views/admin/templates/invalidInputError.php
  src/admin/js/app.js
  src/admin/sass/plugins/_choices.scss
Labels: backend

#128 KIN-303 create certificate functionality [no files functionality yet]
  app/Controllers/CtrlCertificate.php
  app/Models/CertificateModel.php
  app/Models/FileModel.php
  app/Validation/CertificateValidation.php
  app/Views/admin/certificates/CertificateCreate.php
  app/Views/admin/certificates/certificatesFormTemplate.php
  public/uploads/3ea307c224811d55048d72b5696895eb/auth-one-bg.jpg
Labels: backend, private

#123 KIN-259: Delete measurement solutions Functionality [Without Files Logic]
  app/Controllers/CtrlSolution.php
  app/Views/admin/typeSolutions/Solutions.php
Labels: backend, private

#136 KIN-306 delete product alert products page
  app/Controllers/CtrlProduct.php
  app/Views/admin/products/Products.php
Labels: frontend, private
