Repository loopcrack-org/Kinub, pull requests merged in 2023-09, with the labels that each got.

#29 KIN-193 Refactoring of the SendEmail
  app/Controllers/CtrlEmail.php
  app/Utils/EmailSender.php
  app/Views/mailDetail.php
Labels: Backend

#33 KIN-113 Reset password form logic
  app/Controllers/CtrlEmail.php
  app/Database/Seeds/UserSeeder.php
  app/Validation/PasswordEmailValidation.php
  app/Views/login/PasswordEmail.php
  app/Views/login/response.php
  app/Views/templates/emails/passwordReset.php
Labels: Backend, Private

#27 KIN-86 Sending the email of the technical support form
  app/Controllers/CtrlEmail.php
Labels: Backend

#28 KIN-79 Implemented the About Us section on the Home page
  app/Views/public/index.php
  package-lock.json
  public/assets/css/public.min.css
  public/assets/images/auth-one-bg.avif
  public/assets/images/auth-one-bg.webp
  src/sass/public/UI/_index.scss
  src/sass/public/UI/about-us/_about-us.scss
  src/sass/public/UI/about-us/_index.scss
  src/sass/public/base/_variables.scss
Labels: Frontend, Public

#34 Feature/kin 76/footer public view front end
  app/Views/public/templates/footer.php
  app/Views/public/templates/layout.php
  public/assets/css/public.min.css
  public/assets/images/facebook-icon.avif
  public/assets/images/facebook-icon.svg
  public/assets/images/instagram-icon.avif
  public/assets/images/instagram-icon.svg
  public/assets/images/linkedin-icon.avif
  public/assets/images/linkedin-icon.svg
  public/assets/images/youtube-icon.avif
  public/assets/images/youtube-icon.svg
  src/images/facebook-icon.svg
  src/images/instagram-icon.svg
  src/images/linkedin-icon.svg
  src/images/youtube-icon.svg
  src/sass/public/UI/_index.scss
  src/sass/public/UI/footer/_footer.scss
  src/sass/public/UI/footer/_index.scss
  src/sass/public/base/_variables.scss
Labels: Frontend, Public

#35 KIN-187 Change Password Logic
  app/Controllers/CtrlLogin.php
  app/Database/Seeds/UserSeeder.php
  app/Models/UserModel.php
  app/Validation/ChangePasswordValidation.php
  app/Views/login/PasswordReset.php
Labels: Backend, Private

#37 KIN-204 Validate token to reset password
  app/Controllers/CtrlLogin.php
  app/Views/login/PasswordReset.php
Labels: Backend

#39 KIN-144 Storage of technical support form data
  app/Controllers/CtrlEmail.php
Labels: Backend

#38 KIN-199 Routing of Home, Measurement Solutions and Categories pages
  app/Config/Routes.php
  app/Controllers/CtrlCategory.php
  app/Controllers/CtrlHomeSection.php
  app/Controllers/CtrlSolution.php
  app/Models/CategoryModel.php
  app/Models/HomeSectionModel.php
  app/Models/TagModel.php
  app/Models/TypeSolutionModel.php
  app/Views/admin/categories/Categories.php
  app/Views/admin/categories/CategoryCreate.php
  app/Views/admin/categories/CategoryEdit.php
  app/Views/admin/homeSection/HomeSection.php
  app/Views/admin/homeSection/HomeSectionEdit.php
  app/Views/admin/typeSolutions/SolutionCreate.php
  app/Views/admin/typeSolutions/SolutionEdit.php
  app/Views/admin/typeSolutions/Solutions.php
Labels: Backend, Private

#40 KIN-77 Whatsapp button public view front end
  app/Views/public/templates/layout.php
  app/Views/public/templates/whatsapp.php
  public/assets/css/public.min.css
  src/sass/public/UI/_index.scss
  src/sass/public/UI/whatsapp/_index.scss
  src/sass/public/UI/whatsapp/_whatsapp.scss
Labels: Frontend, Public

#42 KIN-85 problem details section layout technical support page front-end
  app/Views/public/index.php
  app/Views/public/support.php
  public/assets/css/public.min.css
  public/assets/js/public/support.js
  src/js/public/support.js
  src/sass/public/UI/_index.scss
  src/sass/public/UI/support/_index.scss
  src/sass/public/UI/support/_support.scss
Labels: Frontend, Public

#45 KIN-182 added product details fieldset to technical support page
  app/Views/public/support.php
  public/assets/css/public.min.css
  public/assets/js/public/support.js
  src/js/public/support.js
  src/sass/public/UI/support/_support.scss
Labels: Frontend, Public

#44 KIN 216 - Category and Tags tables and seeders
  app/Database/Seeds/CategorySeeder.php
  app/Database/Seeds/TagsSeeder.php
  backup/Database.sql
Labels: Database

#36 KIN-76 navigation bar public view front end
  app/Views/public/index.php
  app/Views/public/templates/header.php
  app/Views/public/templates/layout.php
  public/assets/css/public.min.css
  public/assets/images/close.avif
  public/assets/images/close.svg
  public/assets/images/menu.avif
  public/assets/images/menu.svg
  public/assets/js/public/menuMobile.js
  src/images/close.svg
  src/images/menu.svg
  src/js/public/menuMobile.js
  src/sass/public/UI/_index.scss
  src/sass/public/UI/about-us/_about-us.scss
  src/sass/public/UI/form/_form.scss
  src/sass/public/UI/header/_header-mobile.scss
  src/sass/public/UI/header/_header.scss
  src/sass/public/UI/header/_index.scss
  src/sass/public/UI/header/_sidebar.scss
  src/sass/public/UI/whatsapp/_whatsapp.scss
  src/sass/public/base/_mixins.scss
  src/sass/public/base/_variables.scss
Labels: Frontend, Public

#46 KIN-129 Category table view
  app/Views/admin/categories/Categories.php
  app/Views/partials/customizer.php
  app/Views/partials/footer.php
  app/Views/templates/admin/dashboardTemplate.php
  public/assets/js/pages/category.js
  public/assets/js/pages/datatables-general-config.js
Labels: Frontend, Private

#48 KIN-220 Renaming of the emails, email_types and users tables
  app/Database/Seeds/EmailSeeder.php
  app/Database/Seeds/UserSeeder.php
  app/Models/EmailModel.php
  app/Models/UserModel.php
  backup/Database.sql
Labels: Database

#49 KIN-130 Create category view
  app/Views/admin/categories/Categories.php
  app/Views/admin/categories/CategoryCreate.php
  app/Views/templates/admin/dashboardTemplate.php
  public/assets/css/admin.min.css
  public/assets/js/admin/plugins.js
  public/assets/js/pages/category.js
  public/assets/js/pages/datatables-general-config.js
  public/assets/js/pages/form-file-upload-category.init.js
  public/assets/libs/choices.js/public/assets/scripts/choices.min.js
  public/assets/libs/filepond-plugin-file-encode/filepond-plugin-file-encode.min.js
  public/assets/libs/filepond-plugin-file-validate-size/filepond-plugin-file-validate-size.min.js
  public/assets/libs/filepond-plugin-image-exif-orientation/filepond-plugin-image-exif-orientation.min.js
  public/assets/libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.css
  public/assets/libs/filepond-plugin-image-preview/filepond-plugin-image-preview.min.js
  public/assets/libs/filepond/filepond.min.css
  public/assets/libs/filepond/filepond.min.js
  src/js/pages/category.js
  src/js/pages/datatables-general-config.js
  src/js/pages/form-file-upload-category.init.js
  src/sass/admin/config/app.scss
  src/sass/admin/plugins/_choices.scss
Labels: Frontend, Private

#55 KIN-198 Logout
  app/Config/Routes.php
  app/Controllers/CtrlLogin.php
  app/Views/partials/topbar.php
Labels: Backend, Private

#56 KIN-201 Template category form
  app/Views/admin/categories/CategoryCreate.php
  app/Views/admin/categories/categoriesFormTemplate.php
Labels: Frontend, Private

#57 KIN 131 Edit category view categories page
  app/Controllers/CtrlCategory.php
  app/Views/admin/categories/Categories.php
  app/Views/admin/categories/CategoryCreate.php
  app/Views/admin/categories/CategoryEdit.php
Labels: Frontend, Private

#58 KIN-234 Fix footer icon bug
  public/assets/css/public.min.css
  src/sass/public/UI/footer/_footer.scss
Labels: Frontend, Public, bug

#59 KIN-205 Creation of the measurement solution table
  app/Views/admin/categories/Categories.php
  app/Views/admin/categories/CategoryCreate.php
  app/Views/admin/categories/CategoryEdit.php
  app/Views/admin/typeSolutions/Solutions.php
  app/Views/partials/page-title.php
  public/assets/js/pages/measurementSolution.js
  src/js/pages/measurementSolution.js
Labels: Frontend, Private

#60 KIN-218 Add routing access validation in admin and login section
  app/Config/Filters.php
  app/Controllers/CtrlLogin.php
  app/Filters/AdminFilter.php
  app/Filters/AuthFilter.php
  app/Filters/LoginFilter.php
Labels: Backend

#47 KIN-84 added client information fieldset to support page
  app/Views/public/support.php
  public/assets/css/public.min.css
  public/assets/js/public/support.js
  public/assets/libs/vanilla-validator/vanilla-validator-concat.min.js
  src/js/public/support.js
  src/sass/public/UI/footer/_footer.scss
  src/sass/public/UI/form/_form.scss
  src/sass/public/UI/support/_support.scss
  src/sass/public/base/_global.scss
Labels: Frontend, Public

#64 KIN-132 Modal window to delete category
  app/Controllers/CtrlCategory.php
  app/Views/admin/categories/Categories.php
  public/assets/js/admin/alert-deleteElement.js
  src/js/admin/alert-deleteElement.js
Labels: Frontend, Private

#62 KIN-206 Measurement solutions form template measurement solutions page
  app/Views/admin/typeSolutions/SolutionCreate.php
  app/Views/admin/typeSolutions/solutionsFormTemplate.php
Labels: Frontend, Private

#71 KIN-257 Testing Files Functionality
  app/Config/Routes.php
  app/Controllers/CtrlTestFiles.php
  app/Views/admin/test/testFiles.php
  package-lock.json
  package.json
  src/admin/js/pages/testFiles.js
  src/admin/sass/plugins/filepond/filepond.scss
Labels: Frontend, Private

#68 KIN-106 Certificates page layout
  app/Config/Routes.php
  app/Controllers/CtrlPublicPages.php
  app/Views/public/certificates.php
  app/Views/public/templates/pagination.php
  public/assets/images/left-arrow.svg
  public/assets/images/youtube-icon.svg
  src/images/youtube-icon.svg
  src/public/js/menuMobile.js
  src/public/sass/UI/equipments/_equipments.scss
  src/public/sass/base/_mixins.scss
  src/public/sass/certificates.scss
  src/public/sass/pagination.scss
Labels: Frontend, Public
