Repository loopcrack-org/Kinub, pull requests merged in 2023-10, with the labels that each got.

#78 KIN-271 Added live-reloading with BrowserSync
  .env.example
  app/Config/App.php
  gulpfile.js
  package-lock.json
  package.json
Labels: Setup

#76 KIN-239 Fix Routes Language
  app/Config/Routes.php
  app/Controllers/CtrlLogin.php
  app/Views/admin/categories/Categories.php
  app/Views/login/PasswordEmail.php
  app/Views/login/index.php
  app/Views/partials/topbar.php
  app/Views/templates/emails/passwordReset.php
Labels: setup

#73 KIN-258 Database Design Implementation
  app/Controllers/CtrlCategory.php
  app/Controllers/CtrlEmail.php
  app/Controllers/CtrlLogin.php
  app/Database/Seeds/CategorySeeder.php
  app/Database/Seeds/CategoryTagSeeder.php
  app/Database/Seeds/EmailSeeder.php
  app/Database/Seeds/TagsSeeder.php
  app/Database/Seeds/UserSeeder.php
  app/Models/CategoryModel.php
  app/Models/CategoryTagModel.php
  app/Models/EmailModel.php
  app/Models/HomeSectionModel.php
  app/Models/TagModel.php
  app/Models/TypeSolutionModel.php
  app/Models/UserModel.php
  app/Validation/LoginValidation.php
  app/Views/admin/categories/Categories.php
  app/Views/admin/categories/categoriesFormTemplate.php
  backup/Database.sql
Labels: database

#51 KIN-81 added measurement solutions section to homepage
  app/Views/public/index.php
  public/assets/images/icon-example.svg
  src/public/sass/UI/_index.scss
  src/public/sass/UI/measurement-solutions/_card.scss
  src/public/sass/UI/measurement-solutions/_index.scss
  src/public/sass/UI/measurement-solutions/_measurement-solutions.scss
  src/public/sass/base/_variables.scss
Labels: frontend, public

#86 KIN-92 product catalog layout product catalog page front end
  app/Config/Routes.php
  app/Controllers/CtrlPublicPages.php
  app/Views/public/category.php
  public/assets/images/arrow-down.svg
  src/public/js/multiple-options-select.js
  src/public/sass/UI/filter/_filter.scss
  src/public/sass/UI/filter/_index.scss
  src/public/sass/UI/filter/_multiple-options-select.scss
  src/public/sass/UI/pagination/_index.scss
  src/public/sass/base/_mixins.scss
  src/public/sass/category.scss
  src/public/sass/filter.scss
Labels: frontend, public

#84 KIN-142 Create user layout user page
  app/Config/Routes.php
  app/Controllers/CtrlUser.php
  app/Views/admin/categories/CategoryCreate.php
  app/Views/admin/categories/CategoryEdit.php
  app/Views/admin/categories/categoriesFormTemplate.php
  app/Views/admin/typeSolutions/SolutionCreate.php
  app/Views/admin/typeSolutions/solutionsFormTemplate.php
  app/Views/admin/users/UserCreate.php
  app/Views/admin/users/Users.php
  app/Views/partials/page-title.php
  src/admin/js/pages/user.js
Labels: frontend, private

#67 KIN-242 Validation for Ladas
  app/Controllers/CtrlEmail.php
  app/Validation/SupportEmailValidation.php
  app/Views/public/support.php
  package-lock.json
  package.json
  public/assets/images/flags.avif
  public/assets/images/flags.png
  public/assets/images/flags.webp
  public/assets/images/flags@2x.avif
  public/assets/images/flags@2x.png
  public/assets/images/flags@2x.webp
  src/public/js/support.js
  src/public/sass/UI/support/_support.scss
  src/public/sass/plugins/intl-tel-input.scss
Labels: backend, public, bug

#65 KIN-237 Refactor navigation bar implementation
  app/Views/public/templates/header.php
  src/public/js/home.js
  src/public/js/menuMobile.js
  src/public/sass/UI/about-us/_about-us.scss
  src/public/sass/UI/header/_header-mobile.scss
  src/public/sass/UI/header/_header.scss
  src/public/sass/UI/header/_index.scss
  src/public/sass/UI/header/_sidebar.scss
  src/public/sass/base/_global.scss
Labels: frontend, public

#81 KIN-273 added linting and formatting configuration
  .editorconfig
  .eslintignore
  .eslintrc.js
  .github/pr-badge.yml
  .github/workflows/checks.yml
  .gitignore
  .hintrc
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  .php-cs-fixer.dist.php
  .prettierignore
  .prettierrc
  .stylelintignore
  .stylelintrc
  .vscode/README.md
  .vscode/extensions.json
  .vscode/recommended-launch.json
  .vscode/recommended-settings.json
  CONTRIBUTING.md
  README.md
  branch-name-lint.json
  commitlint.config.js
  composer.json
  composer.lock
  lint-staged.config.js
  package-lock.json
  package.json
Labels: setup

#91 KIN-279 configuration fixes and logic changes
  app/Controllers/CtrlEmail.php
  app/Utils/EmailSender.php
  lint-staged.config.js
Labels: backend, private

#89 KIN-275 create user account email
  app/Controllers/CtrlUser.php
  app/Views/templates/emails/createUserAccount.php
Labels: frontend, private

#88 KIN-143 delete user alert
  app/Config/Routes.php
  app/Controllers/CtrlUser.php
  app/Views/admin/categories/Categories.php
  app/Views/admin/users/Users.php
  src/admin/js/alert-deleteElement.js
  src/admin/js/alertElement.js
  src/common/sass/sweetAlert.scss
Labels: frontend, private

#90 KIN-276 adapt login and reset password logic to confirmed accounts
  app/Controllers/CtrlEmail.php
  app/Controllers/CtrlLogin.php
  app/Validation/LoginValidation.php
  app/Validation/PasswordEmailValidation.php
  app/Views/login/PasswordReset.php
Labels: backend, private

#92 KIN-269 Integration of database migrations
  app/Config/Database.php
  app/Database/Migrations/2023-10-17-060334_Files.php
  app/Database/Migrations/2023-10-17-220959_Categories.php
  app/Database/Migrations/2023-10-17-221112_CategoryTags.php
  app/Database/Migrations/2023-10-17-221137_Certificates.php
  app/Database/Migrations/2023-10-17-221601_MeasurementSolutions.php
  app/Database/Migrations/2023-10-17-221633_HomePage.php
  app/Database/Migrations/2023-10-17-221706_Products.php
  app/Database/Migrations/2023-10-17-221724_ProductsFiles.php
  app/Database/Migrations/2023-10-17-221756_ProductsTags.php
  app/Database/Migrations/2023-10-17-221815_ProductsCategoryTags.php
  app/Database/Migrations/2023-10-17-224213_EmailTypes.php
  app/Database/Migrations/2023-10-17-224228_Emails.php
  app/Database/Migrations/2023-10-17-224407_Users.php
  app/Database/Seeds/UserSeeder.php
Labels: database
